# Generated by Django 5.1.7 on 2025-04-20 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_mfa_enabled_user_mfa_secret'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(blank=True, max_length=2000, verbose_name='О себе'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, max_length=100, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Мужской'), ('F', 'Женский')], max_length=1, null=True, verbose_name='Пол'),
        ),
        migrations.AddField(
            model_name='user',
            name='hobbies',
            field=models.CharField(blank=True, max_length=255, verbose_name='Хобби'),
        ),
        migrations.AddField(
            model_name='user',
            name='max_age',
            field=models.PositiveIntegerField(default=60, verbose_name='Максимальный возраст партнера'),
        ),
        migrations.AddField(
            model_name='user',
            name='min_age',
            field=models.PositiveIntegerField(default=18, verbose_name='Минимальный возраст партнера'),
        ),
        migrations.AddField(
            model_name='user',
            name='profile_complete',
            field=models.BooleanField(default=False, verbose_name='Анкета заполнена'),
        ),
        migrations.AddField(
            model_name='user',
            name='seeking',
            field=models.CharField(choices=[('M', 'Мужчин'), ('F', 'Женщин'), ('A', 'Всех')], default='A', max_length=1, verbose_name='Ищу'),
        ),
    ]
