# Generated by Django 5.1.7 on 2025-04-21 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_user_avatar_user_bio_user_birth_date_user_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=128, verbose_name='Имя'),
        ),
    ]
