# Generated by Django 5.1.7 on 2025-04-21 02:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_user_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='fullname',
        ),
    ]
