# Generated by Django 5.1.7 on 2025-04-21 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_name_user_fullname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='name',
        ),
    ]
